name: "Update Fun Facts"
on:
  schedule:
    - cron: "0 0,8,16 * * *" # Runs every 8 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add this line for explicit permissions
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for better compatibility
      
      - name: Update Fun Fact
        run: |
          # Array of fun facts
          facts=(
            "500 kiddo naptimes later, I'm a full-stack developer!"
            "My mama patience (super-power) allows me to debug complex issues!"
            "I've mastered the art of returning to complex code after multiple interruptions!"
            "I've debugged code one-handed while holding a baby in the other!"
            "I've mastered the art of context-switching!"
          )
          
          # Get a random fact
          random_fact="${facts[$RANDOM % ${#facts[@]}]}"
          
          # URL encode the fact (basic version)
          encoded_fact=$(echo "Did you know? $random_fact" | sed 's/ /%20/g' | sed 's/!/%21/g' | sed "s/'/%27/g" | sed 's/(/%28/g' | sed 's/)/%29/g' | sed 's/+/%2B/g' | sed 's/,/%2C/g' | sed 's/-/%2D/g' | sed 's/\./%2E/g' | sed 's/\//%2F/g')
          
          # Check if the placeholder exists
          if grep -q "text=CURRENT_FUN_FACT" README.md; then
            # Update the README with the new fact
            sed -i "s|text=CURRENT_FUN_FACT|text=${encoded_fact}|g" README.md
            echo "Updated placeholder with new fun fact"
          elif grep -q "text=Did%20you%20know%3F" README.md; then
            # If placeholder doesn't exist but there's already a fun fact, replace it
            sed -i "s|text=Did%20you%20know%3F%20[^&]*|text=${encoded_fact}|g" README.md
            echo "Replaced existing fun fact with new one"
          elif grep -q "type=waving.*section=footer" README.md; then
            # If we can find the wave footer but not the text parameter, add it
            sed -i "s|type=waving&color=gradient&customColorList=6,8,9,10,12&height=120&section=footer|type=waving&color=gradient&customColorList=6,8,9,10,12&height=120&section=footer&text=${encoded_fact}|g" README.md
            echo "Added fun fact to existing wave footer"
          else
            echo "Warning: Could not find placeholder or existing fun fact in README.md"
            echo "The wave footer might be missing or in a different format"
            echo "Continuing without updating the fun fact"
            # Exit with 0 to prevent workflow failure
            exit 0
          fi
          
      - name: Commit and Push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update fun fact" || exit 0
          git push
          
      - name: Commit and Push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update fun fact" || exit 0
          git push
