name: "Update Fun Facts"
on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update Fun Fact
        run: |
          # Array of fun facts
          facts=(
            "I debug with rubber ducks!"
            "I once coded for 36 hours straight during a hackathon!"
            "My first program was a text-based adventure game!"
            "I've contributed to over 50 open source projects!"
            "I learned to code on a computer with only 4MB of RAM!"
            "I can type at 120 words per minute!"
            "I built my first website when I was 12 years old!"
            "I've fixed bugs while dreaming about code!"
            "I name my plants after programming languages!"
            "I collect vintage keyboards!"
            "I've written code in 15 different programming languages!"
            "My favorite algorithm is quicksort!"
            "I once refactored an entire codebase during a flight!"
            "I mentor coding newbies in my spare time!"
            "I've participated in 20+ hackathons!"
            "I built an app that reminds me to drink water!"
            "I code best after midnight!"
            "I've written over 1 million lines of code!"
            "I can recite the first 100 digits of Pi!"
            "I've been coding for over a decade!"
          )
          
          # Get a random fact
          random_fact="${facts[$RANDOM % ${#facts[@]}]}"
          
          # Update the README with the new fact
          sed -i "s|text=Did%20you%20know%3F%20.*&fontSize=20|text=Did%20you%20know%3F%20${random_fact// /%20}&fontSize=20|g" README.md
          
      - name: Commit and Push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update fun fact" || exit 0
          git push
