name: GitHub 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Run once a day at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.daaimah-token }}
          USERNAME: ${{ github.daaimah123 }}
          
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated 3D Contribution Graph"
          git push
