ame: GitHub 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Run once a day at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.daaimah-token }}
          USERNAME: daaimah123

      - name: Commit and Push
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A .
          git commit -m "Generated 3D Contribution Graph" || echo "No changes to commit"
          git push
